# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=7)),
                ('participating', models.BooleanField(default=True)),
                ('channel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('artist', models.CharField(db_index=True, max_length=255)),
                ('transcriber', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('updated', models.DateField(db_index=True)),
                ('language', models.CharField(db_index=True, max_length=255)),
                ('length', models.IntegerField(db_index=True)),
                ('preview_start', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.Song'),
        ),
        migrations.AddField(
            model_name='party',
            name='songs',
            field=models.ManyToManyField(through='karaoke.Playlist', to='karaoke.Song'),
        ),
        migrations.AddField(
            model_name='partymember',
            name='party',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='karaoke.Party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partymember',
            name='channel',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='nick',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='colour',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
