# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_song_song_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='updated',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
