# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 02:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_auto_20170826_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.CharField(default='covert.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='parts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
